trigger:
  - main

pool:
  name: 'Default' 
  demands: 
    - agent.name -equals MSI

variables:
  dockerRegistryServiceConnection: 'TEST3'
  imageRepository: 'sebastianperalta/test'
  sonarCloudOrganization: '1105487'
  sonarCloudProjectKey: '1105487_ContainerProject2'
  sonarCloudProjectName: 'ContainerProject2'
  snykToken: $(c37f379e-253c-4d61-aec8-615ec57cd230)

steps:
  # Checkout del repositorio
  - checkout: self

  # Configurar SonarCloud
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'TEST2'
      organization: '1105487'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: '1105487_ContainerProject2'
      cliProjectName: 'ContainerProject2'
      cliSources: '.'
      extraProperties: |
        sonar.java.binaries=**/target/classes
        sonar.java.libraries=**/target/**/*.jar
      sonar.branch.name: 'main'
      

  # Análisis de SonarCloud
  - task: SonarCloudAnalyze@1

  # Publicar resultados de SonarCloud
  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'

  # Construir y empujar la imagen Docker a DockerHub
  - task: Docker@2
    inputs:
      containerRegistry: '$(dockerRegistryServiceConnection)'
      repository: '$(imageRepository)'
      command: 'buildAndPush'
      Dockerfile: 'C:\Users\sebas\Container2\ProyectoFinal\Dockerfile'
      tags: |
        $(Build.BuildId)
